import type { Chapter } from '../types/novel';

export interface MergeRewriteResult {
  /** 合并后的章节；null = 正文已被用户改动，结果不可安全采用 */
  chapter: Chapter | null;
  /** 放弃原因（供 UI 提示） */
  skippedReason?: 'prose-changed';
}

/**
 * 把「AI 修 / 去味」产出的章节安全合并进最新版本。
 *
 * 背景：这些动作的返回值 `r.chapter` 是**基于 pre-await 快照**构造的整章对象，
 * 而 LLM 任务可能持续数分钟。此前的写法
 * `prev.chapters.map((c) => (c.id === id ? r.chapter : c))`
 * 只保护了「其他章」——被操作的**这一章**仍被整章替换，用户在任务期间对本章
 * 正文/标题/梗概/锁定态的编辑被静默回滚。
 *
 * 策略（字段级合并 + 正文指纹闸门）：
 * - **正文指纹变了** → 局部改写的前提（对某段正文做替换）已失效，放弃回写，
 *   由调用方提示用户重试。绝不覆盖用户改动。
 * - **正文未变** → 只回写该动作真正产出的字段，其余字段保留 `latest`（用户最新）。
 *   `memoryAudit` / `revisionTodos` 用**引用相等**判断动作是否真的动过它：
 *   没动过就不回写，避免把用户期间的勾选/状态回滚。
 */
export function mergeRewriteIntoLatest(
  latest: Chapter,
  rewritten: Chapter,
  startedFrom: Chapter
): MergeRewriteResult {
  if (latest.content !== startedFrom.content) {
    return { chapter: null, skippedReason: 'prose-changed' };
  }

  const proseRewritten = rewritten.content !== startedFrom.content;
  return {
    chapter: {
      ...latest,
      // 仅在动作确实改写了正文时回写正文相关字段：纯扫描类动作（如只扫 AI 味）
      // 不碰正文，回写其陈旧的 contentUpdatedAt 只会无谓回退时间戳。
      ...(proseRewritten
        ? {
            content: rewritten.content,
            wordCount: rewritten.wordCount,
            contentUpdatedAt: rewritten.contentUpdatedAt,
          }
        : {}),
      ...(rewritten.lastModified !== startedFrom.lastModified
        ? { lastModified: rewritten.lastModified }
        : {}),
      ...(rewritten.memoryAudit !== startedFrom.memoryAudit
        ? { memoryAudit: rewritten.memoryAudit }
        : {}),
      ...(rewritten.revisionTodos !== startedFrom.revisionTodos
        ? { revisionTodos: rewritten.revisionTodos }
        : {}),
    },
  };
}

/** 待修合并：以管线产出为准，但保留用户在生成期间勾选的状态，用户新增条目也保留 */
export function mergeRevisionTodoStatus(
  latest: Chapter['revisionTodos'],
  produced: Chapter['revisionTodos']
): Chapter['revisionTodos'] {
  if (!latest?.length) return produced;
  if (!produced?.length) return latest;
  const latestById = new Map(latest.map((t) => [t.id, t]));
  const producedIds = new Set(produced.map((t) => t.id));
  const merged = produced.map((t) => {
    const l = latestById.get(t.id);
    return l && l.status !== t.status ? { ...t, status: l.status } : t;
  });
  for (const l of latest) {
    if (!producedIds.has(l.id)) merged.push(l);
  }
  return merged;
}

/**
 * 把管线终稿应用到「最新章节」上——只覆盖管线真正产出的字段。
 *
 * `finalChapter` 是在可能长达数秒的 await（如 `ledgerLlmEnrich` 的事实账本 LLM
 * 补抽）**之前**构造的整章对象；直接整章替换会把用户在这段时间对本章标题/梗概/
 * 作者注等的编辑静默回滚。这里以 `latest` 为底，仅覆盖管线拥有的字段。
 */
export function applyPipelineResult(latest: Chapter, finalChapter: Chapter): Chapter {
  return {
    ...latest,
    content: finalChapter.content,
    wordCount: finalChapter.wordCount,
    status: finalChapter.status,
    locked: finalChapter.locked,
    lockedAt: finalChapter.lockedAt,
    conservativeDraft: finalChapter.conservativeDraft,
    beats: finalChapter.beats,
    memoryAudit: finalChapter.memoryAudit,
    memoryInjection: finalChapter.memoryInjection,
    intent: finalChapter.intent,
    recap: finalChapter.recap,
    memoryWriteLog: finalChapter.memoryWriteLog,
    autoFixCount: finalChapter.autoFixCount,
    autoGenerated: finalChapter.autoGenerated,
    contentUpdatedAt: finalChapter.contentUpdatedAt,
    lastModified: finalChapter.lastModified,
    revisionTodos: mergeRevisionTodoStatus(latest.revisionTodos, finalChapter.revisionTodos),
  };
}
